require 'fileutils'

task :test do
  sh 'ruby test/test_set_hooks.rb'
end

directory '.bundle/deps' do
  sh 'bundle install'
end

task :fmt => '.bundle/deps' do
  # rufo exit with non-zero status when some code needed formatting
  sh 'bundle exec rufo lib test' rescue nil
end

task :check => '.bundle/deps' do
  sh 'bundle exec rufo --check lib test'
end

task :release do
  Dir['set_git_hooks_dir-*.gem'].each{|f| File.delete f }
  sh 'gem build set_git_hooks_dir.gemspec'
  sh "gem push #{Dir['set_git_hooks_dir-*.gem'][0]}"
end

task :clean do
  %w[.bundle/deps .bundle/plugin Gemfile.lock].each{|p| FileUtils.remove_entry(p, force: true) }
  Dir['set_git_hooks_dir-*.gem'].each{|f| File.delete f }
end
