name: CI
on: [push, pull_request]

jobs:
  rust:
    defaults:
      run:
        working-directory: rust
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - run: cargo clippy --tests -- -D warnings
      - run: cargo test
      - run: cargo fmt --all --check
  npm:
    defaults:
      run:
        working-directory: npm
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: npm/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm test -- --timeout 10000
      - run: npm run lint
  python:
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - run: pip install setuptools
      - run: pip install -e .
      - run: python test/test_setup.py
